name: Test
on:
  workflow-dispatch:
  
jobs:
  local-cache:
    name: Setup local-cache version
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: setup-go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.x
          
      - name: setup-go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.x
          check-latest: true
